#ifndef __TOPOLOGYCONTROL_LKTC_H_
#define __TOPOLOGYCONTROL_LKTC_H_

#include "../../app-conf.h"
#include "../../lib/neighbors.h"

#ifndef COMPONENT_TOPOLOGYCONTROL_LKTC_STRETCHFACTOR
#define COMPONENT_TOPOLOGYCONTROL_LKTC_STRETCHFACTOR 1.4
#endif

#ifndef COMPONENT_TOPOLOGYCONTROL_LKTC_UPDATEINTERVAL
#define COMPONENT_TOPOLOGYCONTROL_LKTC_UPDATEINTERVAL 300
#endif

#ifndef COMPONENT_TOPOLOGYCONTROL_LKTC_BROADCASTHOPCOUNT_IMMEDIATE_MIN
#define COMPONENT_TOPOLOGYCONTROL_LKTC_BROADCASTHOPCOUNT_IMMEDIATE_MIN 1
#endif

#ifndef COMPONENT_TOPOLOGYCONTROL_LKTC_BROADCASTHOPCOUNT_IMMEDIATE_MAX
#define COMPONENT_TOPOLOGYCONTROL_LKTC_BROADCASTHOPCOUNT_IMMEDIATE_MAX 10
#endif

#ifndef COMPONENT_TOPOLOGYCONTROL_LKTC_BROADCASTHOPCOUNT_SMALLDELAY_MIN
#define COMPONENT_TOPOLOGYCONTROL_LKTC_BROADCASTHOPCOUNT_SMALLDELAY_MIN 55
#endif

#ifndef COMPONENT_TOPOLOGYCONTROL_LKTC_BROADCASTHOPCOUNT_SMALLDELAY_MAX
#define COMPONENT_TOPOLOGYCONTROL_LKTC_BROADCASTHOPCOUNT_SMALLDELAY_MAX 65
#endif

#ifndef COMPONENT_TOPOLOGYCONTROL_LKTC_BROADCASTHOPCOUNT_PERIODIC_MIN
#define COMPONENT_TOPOLOGYCONTROL_LKTC_BROADCASTHOPCOUNT_PERIODIC_MIN 270
#endif

#ifndef COMPONENT_TOPOLOGYCONTROL_LKTC_BROADCASTHOPCOUNT_PERIODIC_MAX
#define COMPONENT_TOPOLOGYCONTROL_LKTC_BROADCASTHOPCOUNT_PERIODIC_MAX 330
#endif

int lktc_criteria(const neighbor_t *directhop, const neighbor_t *onehop, const neighbor_t *twohop);

#endif /* __TOPOLOGYCONTROL_LKTC_H_ */
