#ifndef __TOPOLOGYCONTROL_LMST_H_
#define __TOPOLOGYCONTROL_LMST_H_

#include "../../app-conf.h"

#ifndef COMPONENT_TOPOLOGYCONTROL_LMST_UPDATEINTERVAL
#define COMPONENT_TOPOLOGYCONTROL_LMST_UPDATEINTERVAL 600
#endif

#endif /* __TOPOLOGYCONTROL_LMST_H_ */
